----Customer & Product Segmentation

--Find the total number of customers by country
	SELECT
		COUNT(customer_key) Total_Customers,
		ISNULL(country, 'UNKNOWN') AS Country
	FROM Customers
	GROUP BY country
	ORDER BY COUNT(customer_key) DESC

--Find the total number of customers by gender
	SELECT 
		COUNT(customer_key) AS Total_Customers,
		gender
	FROM Customers
	GROUP BY gender
	ORDER BY COUNT(customer_key) DESC

--Find the total number of products by category
	SELECT
		COUNT(product_key)TOTAL_Products,
		category
	FROM Products
	GROUP BY category
	ORDER BY COUNT(product_key) DESC

--Find the average product cost within each category
	SELECT
		category,
		MIN(cost) AS Minimum_Cost,
		MAX(cost) AS Maximum_Cost,
		FORMAT(AVG(cost),'N2') AS Average_Cost
	FROM Products
	GROUP BY category

--Find the total revenue generated by each category
	SELECT 
		p.category,
		SUM(s.sales_amount) AS Total_Revenue,
		FORMAT(SUM(s.sales_amount), 'N2') AS Formatted_Total_Revenue
	FROM Sales AS s
	JOIN Products AS p
	ON s.product_key = p.product_key
	GROUP BY p.category
	ORDER BY Total_Revenue DESC
