----Performance & Rankings

--Find the total revenue generated by each individual customer
	SELECT 
		c.customer_key,
		CONCAT(c.first_name, ' ', c.last_name) AS Full_Name,
		ISNULL(c.country, 'UNKNOWN'),
		COUNT(s.order_number) AS Total_Orders,
		SUM(s.sales_amount) AS Total_Revenue
	FROM Customers AS c
	LEFT JOIN Sales AS s
	ON c.customer_key = s.customer_key
	GROUP BY c.customer_key, c.first_name, c.last_name, c.country

--Analyze the distribution of items sold across different countries
	SELECT
		ISNULL(c.country, 'UNKNOWN') AS Country,
		SUM(quantity) AS Total_Sold_Items
	FROM Customers AS c
	LEFT JOIN Sales AS s
	ON c.customer_key = s.customer_key
	GROUP BY c.country
	ORDER BY Total_Sold_Items DESC

--Identify the Top 5 products by total revenue generated
	SELECT 
		TOP 5 SUM(s.sales_amount) AS Total_Sales,
		p.category,
		p.subcategory,
		s.product_key
	FROM Sales AS s
	LEFT JOIN Products AS p
	ON s.product_key = p.product_key
	GROUP BY s.product_key, p.category, p.subcategory
	ORDER BY Total_Sales DESC

--Identify the Bottom 5 products by total revenue — worst performers
	SELECT 
		TOP 5
		SUM(sales_amount) AS Total_Sales,
		p.category,
		p.subcategory,
		s.product_key
	FROM Sales AS s
	LEFT JOIN Products AS p
	ON s.product_key = p.product_key
	GROUP BY s.product_key, p.category, p.subcategory
	ORDER BY Total_Sales ASC
	 